#!/usr/bin/env python3
from pathlib import Path
import subprocess, tempfile, struct
root=Path(__file__).resolve().parents[2]
base=root/'app/src/main/windows/openxr_runtime/unix'
text='// Generated by tools/xr-packing/build-shaders.py.\n#pragma once\n#include <stdint.h>\n'
with tempfile.TemporaryDirectory() as tmp:
    for name,path in [('gn_pack_vertex',base/'foveated_pack.vert'),('gn_pack_fragment',base/'foveated_pack.frag')]:
        out=Path(tmp)/'shader.spv'
        subprocess.run(['glslangValidator','-V','--target-env','vulkan1.1',str(path),'-o',str(out)],check=True)
        subprocess.run(['spirv-val','--target-env','vulkan1.1',str(out)],check=True)
        data=out.read_bytes();words=struct.unpack('<%dI'%(len(data)//4),data)
        text+='static const uint32_t '+name+'[] = {\n'
        text+='\n'.join(','.join('0x%08xu'%w for w in words[i:i+8])+',' for i in range(0,len(words),8))+'\n};\n'
(base/'foveated_pack_spv.h').write_text(text)
