#!/usr/bin/env python3
"""Reproducibly compile the optical-flow backend's bundled shaders."""
from pathlib import Path
import struct, subprocess, tempfile
base=Path(__file__).resolve().parents[2]/'app/src/main/cpp/xrimmersive/opticalflow'
lines=['// Generated by tools/xr-opticalflow/build-shaders.py', '#pragma once', '#include <cstdint>', 'namespace xrimmersive::windowsvr::opticalflow {']
with tempfile.TemporaryDirectory() as tmp:
    for name, source, defines in [
        (n,n,[]) for n in ['pyramid','pack_flow','luma','search','filter','refine','synthesize']
    ] + [('lumaCompact','luma',['COMPACT_LUMA']),('pyramidCompact','pyramid',['COMPACT_LUMA']),
         ('searchSubgroup','search',['NATIVE_SUBGROUP']),
         ('filterFloat','filter',['FILTERED_FLOW']),
         ('synthesizeFloat','synthesize',['FILTERED_FLOW'])]:
        spv=Path(tmp)/(name+'.spv')
        subprocess.run(['glslangValidator','-V','--target-env','vulkan1.1','-I'+str(base),*['-D'+d+'=1' for d in defines],str(base/(source+'.comp')),'-o',str(spv)],check=True)
        subprocess.run(['spirv-val','--target-env','vulkan1.1',str(spv)],check=True)
        data=spv.read_bytes(); words=struct.unpack('<%dI'%(len(data)//4),data)
        lines.append('inline constexpr uint32_t '+name+'Spv[] = {')
        lines += [','.join('0x%08xu'%w for w in words[i:i+8])+',' for i in range(0,len(words),8)]
        lines.append('};')
lines.append('}')
(base/'shaders_spv.h').write_text('\n'.join(lines)+'\n')
