#!/usr/bin/env python3
"""Regenerate the embedded Vulkan capture shader using glslangValidator."""
from pathlib import Path
import struct
import subprocess
import tempfile
root = Path(__file__).resolve().parents[2]
base = root / 'app/src/main/cpp/xrimmersive'
with tempfile.TemporaryDirectory() as tmp:
    spv = Path(tmp) / 'capture.spv'
    subprocess.run(['glslangValidator', '-V', '--target-env', 'vulkan1.1',
                    str(base / 'xr_lsfg_capture.comp'), '-o', str(spv)], check=True)
    subprocess.run(['spirv-val', '--target-env', 'vulkan1.1', str(spv)], check=True)
    data = spv.read_bytes()
words = struct.unpack('<%dI' % (len(data) // 4), data)
lines = [', '.join('0x%08xu' % w for w in words[i:i+8]) + ',' for i in range(0, len(words), 8)]
(base / 'xr_lsfg_capture_spv.h').write_text(
    '// Generated by tools/xr-lsfg/build-capture-shader.py; edit xr_lsfg_capture.comp.\n'
    '#pragma once\n#include <cstdint>\nnamespace xrimmersive::windowsvr {\n'
    'inline constexpr uint32_t kCaptureSpv[] = {\n' + '\n'.join(lines) + '\n};\n}\n')
